
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 28 23:18:34 EST 2015
//----------------------------------------------------

package com.quadworkshop.kiorpesc;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TEXT_SECTION = 3;
  public static final int IDENT = 9;
  public static final int DATA_SECTION = 2;
  public static final int J_TYPE = 6;
  public static final int EOL = 11;
  public static final int REGISTER = 7;
  public static final int STRING_LITERAL = 13;
  public static final int LABEL = 8;
  public static final int EOF = 0;
  public static final int R_TYPE = 4;
  public static final int TYPE = 10;
  public static final int error = 1;
  public static final int I_TYPE = 5;
  public static final int INTEGER_LITERAL = 12;
}

